services:
  my_service:
    image: rtexa/ml-group-37-tech-challenge-01:latest
    restart: unless-stopped
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/ml-group-37-tech-challenge-01/data:/data
    ports:
      - 9123:8000

  watchtower:
      image: containrrr/watchtower
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --cleanup --interval 60
